;-------------------------------------------------------------------------------
; 藥物縮寫
;-------------------------------------------------------------------------------


:*?ct:Abilify,,::Abilify (aripiprazole 2mg 10mg)
:*?ct:Abimay,,::Abimay (aripiprazole 20mg)
:*?ct:Actein,,::Actein (Acetylcysteine)
:*?ct:Alepan,,::Alepan (oxazepam 15mg)
:*?ct:Alprazolam,,::Alprazolam (0.5mg)
:*?ct:Allegra,,::Allegra (fexofenadine 60mg)
:*?ct:Amaryl,,::Amaryl (glimepiride 2mg)
:*?ct:Antica,,::Antica (Orciprenaline,Bromhexine,Doxylamine)
:*?ct:Antol,,::Antol eye drops (10mg/mL)
:*?ct:Anxicam,,::Anxicam (lorazepam 2mg)
:*?ct:Apa-Risdol,,::Apa-Risdol (risperidone 2mg)
:*?ct:Aprovel,,::Aprovel (irbesartan 300mg)
:*?ct:Aricept,,::Aricept (donepezil 10mg)
:*?ct:Ativan,,::Ativan (lorazepam 0.5mg)
:*?ct:Binin-U,,::Binin-U (haloperidol 5mg)
:*?ct:Biperin,,::Biperin (biperiden 2mg)
:*?ct:Bisacodyl,,::Bisacodyl (10mg)
:*?ct:Brexa,,::Brexa (olanzapine 10mg)
:*?ct:Bricanyl,,::Bricanyl (terbutaline)
:*?ct:Brintellix,,::Brintellix (vortioxetine 10mg)
:*?ct:Cardolol,,::Cardolol (propranolol 10mg)
:*?ct:Caduet,,::Caduet (amlodipine 5mg + atorvastatin 20mg)
:*?ct:Clonopam,,::Clonopam (clonazepam 0.5mg)
:*?ct:Clopine,,::Clopine (clozapine 25mg)
:*?ct:Clozaril,,::Clozaril (clozapine 100mg)
:*?ct:Colchicine,,::Colchicine (0.5mg)
:*?ct:Combivent,,::Combivent (Ipratropium,Salbutamol)
:*?ct:Compesolon,,::Compesolon (prednisolone 5mg)
:*?ct:Cough Mixture,,::Cough Mixture (Platycodon Fluid Extract)
:*?ct:Crestor,,::Crestor (rosuvastatin 10mg)
:*?ct:Curam,,::Curam (amoxicillin & clavulanate)
:*?ct:Cymbalta,,::Cymbalta (duloxetine 30mg)
:*?ct:Cytadine,,::Cytadine (cyproheptadine)
:*?ct:Dalmadorm,,::Dalmadorm (flurazepam 30mg)
:*?ct:Dayvigo,,::Dayvigo (lemborexant 5mg)
:*?ct:Deanxit,,::Deanxit (flupentixol 0.5mg & melitracen 10mg)
:*?ct:Depakine,,::Depakine (valproate 500mg)
:*?ct:Diovan,,::Diovan (valsartan 160mg)
:*?ct:Diphenidol,,::Diphenidol (25mg)
:*?ct:Dogmatyl,,::Dogmatyl (sulpiride 50mg)
:*?ct:Dopadine,,::Dopadine (amantadine 100mg)
:*?ct:Dostinex,,::Dostinex (cabergoline 0.5mg)
:*?ct:Dulcolax,,::Dulcolax (bisacodyl 5mg)
:*?ct:Edarbi,,::Edarbi (azilsartan 40mg)
:*?ct:Efexor,,::Efexor XR (venlafaxine 37.5mg)
:*?ct:Eltroxin,,::Eltroxin (levothyroxine 50mcg)
:*?ct:Epram,,::Epram (escitalopram 10mg)
:*?ct:Era,,::Era (fludiazepam 0.25mg)
:*?ct:Eszo,,::Eszo (estazolam 2mg)
:*?ct:Etumine,,::Etumine (clotiapine 40mg)
:*?ct:Eurodin,,::Eurodin (estazolam 2mg)
:*?ct:Exelon,,::Exelon (rivastigmine)
:*?ct:Exforge,,::Exforge (amlodipine 5mg + valsartan 160mg)
:*?ct:Exforge_HCT,,::Exforge_HCT (amlodipine 5mg + valsartan 160mg + hydrochlorothiazide 12.5mg)
:*?ct:Fallep,,::Fallep (flunitrazepam 2mg)
:*?ct:Famotidine,,::Famotidine (20mg)
:*?ct:Flixotide,,::Flixotide (fluticasone)
:*?ct:Fluronin,,::Fluoronin (fluoxetine 20mg)
:*?ct:Fluanxol,,::Fluanxol (flupentixol 3mg)20mg)
:*?ct:Forxiga,,::Forxiga (dapagliflozin 10mg)
:*?ct:Genclone,,::Genclone (zolpiclone 7.5mg)
:*?ct:Geodon,,::Geodon(ziprasidone 60mg)
:*?ct:Glycopyrodyn,,::Glycopyrodyn (glycopyrrolate 1mg)
:*?ct:Hiros,,::Hiros S.R.M. (Pseudoephedrine 120mg+Cetirizine 5mg)
:*?ct:Haldol,,::Haldol (haloperidol 5mg)
:*?ct:Harnalidge,,::Harnalidge (tamsulosin 0.4mg)
:*?ct:Herbesser,,::Herbesser (diltiazem 30mg)
:*?ct:Hi-Beston,,::Hi-Beston (50mg)
:*?ct:Invega,,::Invega (paliperidone)
:*?ct:Invega ER,,::Invega_ER (paliperidone 3mg 9mg)
:*?ct:Iwell,,::Iwell (50+450mg)
:*?ct:Januvia,,::Januvia (sitagliptin 100mg)
:*?ct:Kascoal,,::Kascoal (dimethicone 40mg)
:*?ct:Kotang,,::Kotang XR (metformin 500mg)
:*?ct:K.B.T,,::K.B.T (Kaolin & Bismuth) 
:*?ct:K-Glu,,::K-Glu (20mEq/15mL)
:*?ct:Lac-B,,::Lac-B (Lactobacillus bifidus) 
:*?ct:Lamictal,,::Lamictal (lamotrigine 50mg)
:*?ct:Latuda,,::Latuda (lurasidone 40mg)
:*?ct:Lendormin,,::Lendormin (brotizolam 0.25mg)
:*?ct:Lepax,,::Lepax (escitalopram 10mg)
:*?ct:Lexapro,,::Lexapro (escitalopram 20mg)
:*?ct:Levozine,,::Levozine (levocetirizine 5mg)
:*?ct:Lipitor,,::Lipitor (atorvastatin 20mg)
:*?ct:Lithcan,,::Lithcan (Lithium 300mg)
:*?ct:Loperan,,::Loperan (loperamide 2mg)
:*?ct:Lorapseudo,,::Lorapseudo SR 5/120 (loratadine 5mg + pseudoephedrine 120mg)
:*?ct:Lorazepam,,::Lorazepam (1mg)
:*?ct:Luvox,,::Luvox (fluvoxamine 50mg)
:*?ct:Lyrica,,::Lyrica (pregabalin 75mg)
:*?ct:Madopar,,::Madopar (benserazide 50mg + levodopa 200mg)
:*?ct:Mebever,,::Mebever (mebeverine 135mg)
:*?ct:Megazon,,::Megazon_PR(quetiapine 50mg)
:*?ct:Meitifen,,::Meitifen (diclofenac 75mg)
:*?ct:Meptin,,::Meptin (Procaterol)
:*?ct:Mesyrel,,::Mesyrel (trazodone 50mg)
:*?ct:Methyl-Eph,,::Methyl-Eph (Methylephedrine)
:*?ct:MgO,,::MgO (250mg)
:*?ct:Midorine,,::Midorine (2.5mg)
:*?ct:Minirin,,::Minirin (desmopressin 0.1mg)
:*?ct:Mirtapine,,::Mirtapine (mirtazapine 30mg)
:*?ct:Mopride,,::Mopride (mosapride 5mg)
:*?ct:Norvasc,,::Norvasc (amlodipine 5mg) 
:*?ct:Novamin,,::Novamin (prochlorperazine 5mg)
:*?ct:Pantoloc,,::Pantoloc GR (pantoprazole 40mg)
:*?ct:Paramol,,::Paramol (acetaminophen 500mg)
:*?ct:Peace,,::Peace (Tripolidine & Pseudoephedrine) 
:*?ct:Propranolol,,::Propranolol (10mg)
:*?ct:Prozac,,::Prozac (fluoxetine 20mg)
:*?ct:Quetia,,::Quetia (quetiapine 200mg)
:*?ct:Quelip,,::Quelip XR (quetiapine 200mg)
:*?ct:Regrow,,::Regrow (dextromethorphan 60mg)
:*?ct:Rexulti,,::Rexulti (brexpiprazole 2mg)
:*?ct:Risperdal,,::Risperdal (risperidone 2mg 1mg/mL)
:*?ct:Ritalin,,::Ritalin (methylphenidate 10mg)
:*?ct:Rivotril,,::Rivotril (clonazepam 0.5mg)
:*?ct:Sennapur,,::Sennapur (Sennoside A+B 12.5mg)
:*?ct:Senokot,,::Senokot (sennosides 7.5mg) 
:*?ct:Sermion,,::Sermion (nicergoline 10mg)
:*?ct:Seroxat,,::Seroxat_CR (paroxetine 12.5mg)
:*?ct:Silence,,::Silence (lorazepam 1mg)
:*?ct:Smecta,,::Smecta (Dioctahedral Smectite) 
:*?ct:Sodicon,,::Sodicon (Glyceryl guaiacolate & Dextromethorphan)
:*?ct:Solaxin,,::Solaxin (chlorzoxazone 200mg)
:*?ct:Solian,,::Solian (amisulpride 200mg)
:*?ct:Soma,,::Soma (chlorzoxazone 150mg + acetaminophen 250mg)
:*?ct:Strattera,,::Strattera (atomoxetine)
:*?ct:Stilnox,,::Stilnox CR (Zolpidem 6.25mg)
:*?ct:Sulpin,,::Sulpin (sulpiride 200mg)
:*?ct:Sume,,::Sume (flunitrazepam 2mg)
:*?ct:Switane,,::Switane (trihexyphenidyl 2mg)
:*?ct:Takepron,,::Takepron (lansoprazole 30mg)
:*?ct:Tegretol,,::Tegretol C-R (carbamazepine C-R 200mg)
:*?ct:Through,,::Through (Sennoside A+B 12mg)
:*?ct:Topamax,,::Topamax (topiramate 25mg/100mg)
:*?ct:Tramacet,,::Tramacet (tramadol[37.5mg]/acetaminophen[325mg])
:*?ct:Tramadol,,::Tramadol MR (200mg)
:*?ct:Trileptal,,::Trileptal (oxcarbazepine 300mg)
:*?ct:Utapine,,::Utapine (quetiapine 25mg)
:*?ct:Valdoxan,,::Valdoxan (agomelatine 25mg)
:*?ct:Venina,,::Venina (estradiol 1mg + medroxyprogesterone 2.5mg)
:*?ct:Vistaril,,::Vistaril (hydroxyzine 25mg)
:*?ct:Volna-K,,::Volna-K (diclofenac 25mg)
:*?ct:Voren-K,,::Voren-K S.C. Tab(diclofenac 25mg)
:*?ct:Wellbutrin,,::Wellbutrin XL (bupropion 150mg)
:*?ct:Zapine,,::Zapine (clozapine 100mg)
:*?ct:Zoloft,,::Zoloft (sertraline 50mg)
:*?ct:Zolpidem,,::Zolpidem (10mg)
:*?ct:Zyprexa,,::Zyprexa Zydis (olanzapine 5mg)