#Include "%A_ScriptDir%\HIS-OPD\HIS-OPD--Variables-EMR-Templates.ahk"
#Include "%A_ScriptDir%\HIS-OPD\HIS-OPD--Variables-NHI-Codes.ahk"
#Include "%A_ScriptDir%\HIS-OPD\HIS-OPD--Variables-UI-Elements.ahk"
#Include "%A_ScriptDir%\HIS-OPD\HIS-OPD--Functions.ahk"
#Include "%A_ScriptDir%\HIS-OPD\HIS-OPD--Menu.ahk"